name: Locize Version Published Workflow

on:
  push:
    branches: [main]
  repository_dispatch:
    types: [locize/versionPublished]

jobs:
  locize_update:
    name: Process Locize Version Published Event
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Dispatch Payload
        run: |
          echo "Received Version: ${{ github.event.client_payload.payload.version }}"
          echo "Full Payload: ${{ toJson(github.event.client_payload) }}"
      - name: Download Translations from locize
        uses: locize/download@v1
        with:
          project-id: ${{ secrets.LOCIZE_PROJECT_ID }}
          version: ${{ github.event.client_payload.payload.version }}
          path: "client/src/locales"
          path-mask: "{{language}}/{{namespace}}"
          clean: true # Ensures old translation files are removed before downloading new ones

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v7.0.6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update translations from locize"
          branch: locize-update-${{ github.event.client_payload.payload.version }}
          delete-branch: true
          title: "chore: update translations from locize"
          body: |
            This PR updates translations from locize.
            - Version: `${{ github.event.client_payload.payload.version }}`
            - Automated update from GitHub Actions
          labels: "translations, automated"
          draft: false

      - name: Check PR Outputs
        if: steps.create_pr.outputs.pull-request-number
        run: |
          echo "Pull Request Number - ${{ steps.create_pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.create_pr.outputs.pull-request-url }}"